### ISSUE TITLE
Get IDE to run on a PI

### ISSUE THREAD

**Issue by Zacharyprime** [kipr/KIDE#1]

**Comment by erinharrington-12** [comment]
Got this technically done - KIDE has to be accessed over the pi's web server (localhost:3000) after building on the computer and transfered /dist/ to the pi. Building while ssh'd into the pi doesn't work as it takes a really long time. The server also has to be ran from the pi to be able to connect to localhost:3000.

Going to keep this issue open as it's "technically" done but probably not exactly what we want.

**Comment by erinharrington-12** [comment]
After further discussion, this issue has been finished. 
Building and running from the Pi was not feasible, so the current solution is to build on a dev machine, transfer /dist/ folder from build to Pi and run the server. 
This solution requires copying /dist/ into Pi each time a change is made - will be solved in a future update in KIPR-Update shell script.

One command that might be needed due to a JavaScript Heap Error - "export NODE_OPTIONS="--max-old-space-size=8192"
